### ISSUE TITLE
Function call changes in TypeScript 4.4 seem to be breaking detection of named exports

### ISSUE THREAD

**Issue by BenSjoberg** [nodejs/cjs-module-lexer#63]
Hi, I'm hoping this is the right place to post this! I just learned about this project when investigating an issue with named imports in NestJS.

TypeScript made a [change](https://github.com/microsoft/TypeScript/pull/44624) to how certain function calls are compiled to CommonJS in version 4.4. Long story short, when you write `export * from "./foo";` in TypeScript, in 4.3 and earlier it would write something like:

    tslib_1.__exportStar(require("./foo"), exports);

But in 4.4 it's writing:

    (0, tslib_1.__exportStar)(require("./foo"), exports);

I ran into this while investigating [an issue I ran into](https://github.com/nestjs/nest/issues/8320) when upgrading NestJS, and [it seems others are experiencing the same problems with other packages](https://github.com/microsoft/TypeScript/issues/45813).

Like I said, I'm not very familiar with this project, but is it possible that the parsing code could be updated to handle this new syntax? I expect this is going to affect more and more CommonJS projects written in TypeScript as they release new versions compiled with 4.4 or later.

**Comment by BenSjoberg** [comment]
> The problem is if this is fixed, as a user you will then be surprised when your package doesn't work on Node.js 14 / Node.js 12. Everything is fine then suddenly you get an issue from a user running your library in a Lambda.

Since those versions are still under LTS, would it be possible to backport the changes in this library to those versions of Node? (I guess that's a question for the Node.js team.) I get that it might take some time for everyone to update, but it feels like the lesser of two evils to me. Due to the TypeScript change (assuming they don't implement a fix), every TypeScript-compiled CommonJS library is going to have its named exports done via `export * from 'foo'` stop working from ESM over time, as maintainers upgrade to TS 4.4+. This is especially frustrating because I assume most package maintainers won't consider upgrading from TS 4.3 to 4.4 to be semver-major change for their package. (That's what brought my attention to this issue in the first place.) This could lead to scenarios where an ESM library stops working when an in-range update to a CJS library releases a new version compiled with TS 4.4+.

I completely understand your hesitancy though. Especially because there's no guarantee a future version of TS (or some other tool) won't change things again.

> Note you can just do [...] And that will always work.

I know. I just wish that auto-imports would that way when working with CJS modules in ESM code. It's frustrating to write code that your editor (& the TypeScript compiler) thinks will work, that fails at runtime. Probably easier said than done though!

**Comment by guybedford** [comment]
This has been resolved thanks to https://github.com/microsoft/TypeScript/pull/47070.
