### ISSUE TITLE
When trying to build with snowpack this error is thrown

### ISSUE THREAD

**Issue by trancephorm** [nodejs/cjs-module-lexer#67]
[21:51:17] [snowpack] Build Result Error: There was a problem with a file build result.
[21:51:17] [snowpack] Parse error @:13:78
[21:51:17] [snowpack] Error: Parse error @:13:78
    at parse (/home/pyc/ttwww/node_modules/es-module-lexer/dist/lexer.cjs:1:402)

Is there any help to it?

**Comment by guybedford** [comment]
If snowpack is using this project, one thing that would help the error message is to pass the second argument as the file name where they are calling into es-module-lexer. Then the `@` in the above message would be the filename causing the parse issue, allowing seeing what character is failing the parse. It may well be JSX or TypeScript syntax causing it though. I'd suggest posting an issue on the relevant repo directly for more information.

**Comment by trancephorm** [comment]
Thanks for your reply. I'm pretty new to this so I don't know where exactly that second argument should be passed.
is that somewhere around here?

$ grep es-module-lexer * -R
node_modules/snowpack/lib/esm/scan-imports.js:import { init as initESModuleLexer, parse } from 'es-module-lexer';
node_modules/snowpack/lib/esm/rewrite-imports.js:const { parse } = require('es-module-lexer');
node_modules/snowpack/lib/esm/lexer-util.js: * Adopted from https://github.com/guybedford/es-module-lexer
node_modules/snowpack/lib/esm/scan-imports.d.ts:import { ImportSpecifier } from 'es-module-lexer';
node_modules/snowpack/lib/cjs/scan-imports.js:const es_module_lexer_1 = require("es-module-lexer");
node_modules/snowpack/lib/cjs/rewrite-imports.js:const { parse } = require('es-module-lexer');
node_modules/snowpack/lib/cjs/lexer-util.js: * Adopted from https://github.com/guybedford/es-module-lexer
node_modules/snowpack/lib/cjs/scan-imports.d.ts:import { ImportSpecifier } from 'es-module-lexer';

**Comment by guybedford** [comment]
@trancephorm yes it's the second argument to that `parse` function that is imported.

**Comment by trancephorm** [comment]
I'll be honest: I don't have a clue what to do. :) But it doesn't matter, thanks anyways.
