### ISSUE TITLE
Bug: cannot detect exported numbers

### ISSUE THREAD

**Issue by hanayashiki** [nodejs/cjs-module-lexer#75]
```js
module.exports = {
  a: 1,
};

module.exports = {
  b,
};
```

Hi, I like this library for its speed and simplicity!

There seems to be a very unexpected bug, when `module.exports` is set to an object that contains a number as its value, the key is not detected as a named export. But in the basic case like `module.exports = { b }`, it works soundly.

I also built a simple playground for this awesome library, and here is the reproduction for this bug:

https://cjs-module-lexer-playground.vercel.app?code=bW9kdWxlLmV4cG9ydHMgPSB7CiAgYTogMSwKfTsKCm1vZHVsZS5leHBvcnRzID0gewogIGIsCn07

The output is 
```json
{
  "exports": [
    "b"
  ],
  "reexports": []
}
```

but we expect `"a"` to be in exports

**Comment by wangchuan95** [comment]
I met same problem, and there are some types can be detected.

```javascript
module.exports = {
  a: true,
  b: null,
  c: undefined,
  d: function () {},
};
```

**Comment by aduh95** [comment]
Probably because of https://github.com/nodejs/cjs-module-lexer/blob/182e2768a4029365144d287257be0ca606c0ab40/README.md?plain=1#L19

**Comment by jaggli** [comment]
@hanayashiki why closing it? The lexer is wrong... It's not about adding new detection patterns, it's about "not crashing when some funny values show up". I mean, we don't care about values (of any case if an object literal is exported..)

Would you like me to do a PR? I could fix it, but i want to make sure, if it has any chance to be merged...

**Comment by hanayashiki** [comment]
> @hanayashiki why closing it? The lexer is wrong... It's not about adding new detection patterns, it's about "not crashing when some funny values show up". I mean, we don't care about values (of any case if an object literal is exported..)
> 
> Would you like me to do a PR? I could fix it, but i want to make sure, if it has any chance to be merged...

it says no new patterns should be added
