### ISSUE TITLE
Issue with parsing 'react-transition-group'

### ISSUE THREAD

**Issue by sceptre12** [nodejs/cjs-module-lexer#77]
Hello I'm having an issue parsing the 'react-transition-group' library.
I'm using react-transition-group version: "^2.6.1"

When attempting to parse the "react-transition-group/index.js " file that contains the content below:

```
"use strict";

var _CSSTransition = _interopRequireDefault(require("./CSSTransition"));

var _ReplaceTransition = _interopRequireDefault(require("./ReplaceTransition"));

var _TransitionGroup = _interopRequireDefault(require("./TransitionGroup"));

var _Transition = _interopRequireDefault(require("./Transition"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

module.exports = {
  Transition: _Transition.default,
  TransitionGroup: _TransitionGroup.default,
  ReplaceTransition: _ReplaceTransition.default,
  CSSTransition: _CSSTransition.default
};
```

Parsing example:

```
const { parse } = require('cjs-module-lexer');
const result = parse([The string above]);

```

The output I get is: result.exports = `[Transition]`

When I remove the default from this: `_Transition.default` 
So it's now `_Transition`

the output from the parse is now:
result.exports =` [Transition, TransitionGroup]`

Is the parsing stopping the moment it finds a default inside of a module.exports object?

**Comment by guybedford** [comment]
Yes this is correct and by design, parsing on `module.exports = { ... }` internals stops the moment you use a `.` within the `...` part since it does not do complete expression parsing.

**Comment by sceptre12** [comment]
Ohh dang.. is there any way around this?
