### ISSUE TITLE
Add RISC-V Support

### ISSUE THREAD

**Issue by thepiwo** [nodejs/cjs-module-lexer#86]
As discussed here https://github.com/vitejs/vite/discussions/13198 it seems there is no risc-v support for this in https://unofficial-builds.nodejs.org/

I am not sure whats the root cause of this, but it seems this package is possible - even if not as performant - to work in 100% nodejs without native binaries, so it should be possible to add support for risc-v using that.

**Comment by guybedford** [comment]
Can you try the same case in the latest version of Node.js? This should have been fixed in https://github.com/nodejs/node/pull/43612.

**Comment by thepiwo** [comment]
Indeed everything is working using node 20
